### ISSUE TITLE
Deploy rosset on AKS using fileshare error

### ISSUE THREAD

**Issue by mottimalka** [rosette-api/helm#5]
We are trying to deploy a rosette on K8S using Persistent Volume with Azure File Share for some reason getting a configuration error:

```
=== Configuration errors:
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/nlp4j/1.2.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rli/7.22.2.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rex/7.46.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rex/7.46.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rex/7.46.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/ascent/1.3.4.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/tcat/2.0.7.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/tvec/4.4.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/tvec/4.4.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/tvec/4.4.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rct/3.0.7.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rbl/7.34.3.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/rex/7.46.0.c62.2 does not exist.
                PreflightWorkerConfigCheck: Root directory /rosette/server/bin/../roots/topics/1.0.0.c62.2 does not exist.
```
 
Here the deployment : 
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosent-rosent-pv
  namespace: rosent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rosent
      app.kubernetes.io/name: rosent-pv
      env: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rosent
        app.kubernetes.io/name: rosent-pv
        env: test
    spec:
      volumes:
        - name: pv-roots-storage
          persistentVolumeClaim:
            claimName: rosent-rosent-pv-roots
        - name: pv-config-storage
          configMap:
            name: rosent-rosent-pv-config
            defaultMode: 420
        - name: pv-config-rosapi-storage
          configMap:
            name: rosent-rosent-pv-config-rosapi
            defaultMode: 420
      containers:
        - name: rosent-pv-container
          image: rosette/server-enterprise:1.16.1
          command:
            - /bin/bash
            - '-c'
          args:
            - >-
              chmod ug+x /rosette/server/bin/update_k8s_config.sh &&
              /rosette/server/bin/update_k8s_config.sh &&
              /rosette/server/bin/launch.sh console
          ports:
            - name: rosent-server
              containerPort: 8181
              protocol: TCP
          env:
            - name: ROSETTE_JVM_MAX_HEAP
              value: '4'
          resources: {}
          volumeMounts:
            - name: pv-roots-storage
              mountPath: /var/nfsshare/roots
            - name: pv-config-storage
              mountPath: /rosette/server/launcher/config
            - name: pv-config-rosapi-storage
              mountPath: /rosette/server/launcher/config/rosapi
          livenessProbe:
            httpGet:
              path: /rest/metrics/health/worker
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /rest/metrics/health/worker
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

```
